version: '3'
services:
  redis:
    image: redis:latest
    hostname: redis
  web:
    build:
      context: .
      dockerfile: Dockerfile
    hostname: web
    command: gunicorn --workers 3 --bind 0.0.0.0:5000 wsgi:app
    volumes:
      - .:/app
    expose:
      - 5000
    links:
      - redis
  worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A youtube_screen_grab.views worker -l INFO
    volumes:
      - .:/app
    links:
      - redis
    depends_on:
      - redis
  nginx:
    build: ./nginx
    ports:
      - 80:80
    depends_on:
      - web
