version: '3'
services:
  redis:
    image: redis:latest
    hostname: redis
  web:
    build:
      context: .
      dockerfile: Dockerfile
    hostname: web
    command: ./scripts/run_web.sh
    volumes:
      - .:/app
    expose:
      - "5000:5000"
    links:
      - redis
  worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: ./scripts/run_celery.sh
    volumes:
      - .:/app
    links:
      - redis
    depends_on:
      - redis
  nginx:
    build: ./nginx
    ports:
      - 1337:80
    depends_on:
      - web
